sudo: false
language: node_js
node_js:
  - "10"

os:
  - linux

script:
  - npm run build
  - npm run test

env: TASK=test
install: cd test && npm ci --ignore-scripts

after_success:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ $(echo $TRAVIS_NODE_VERSION | cut -d'.' -f1) == "10" ]]; then npm run coverage:ci; fi

matrix:
  include:
    - node_js: "10"
      os: linux
      env:
        - TASK=test-couchdb
        - CLOUDANT_DATABASE=testdb
        - CLOUDANT_USER=admin
        - CLOUDANT_PASSWORD=pass
        - CLOUDANT_PORT=5984
      services:
        - couchdb
      before_script:
        - curl http://localhost:5984
        - curl -X PUT http://localhost:5984/_node/couchdb@localhost/_config/admins/admin -d '\"pass\"'
        # - curl -s -X PUT http://localhost:5984/_config/admins/admin -d '"pass"'
        # - curl -X PUT http://localhost:5984/testdb

      script:
        - npm run test

branches:
  only:
    - master
