sudo: false
language: node_js
node_js:
  - "10"

os:
  - linux

script:
  - npm run build
  - npm run test

env: TASK=test
install: cd test && npm ci --ignore-scripts && npm run docker:setup

after_success:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ $(echo $TRAVIS_NODE_VERSION | cut -d'.' -f1) == "10" ]]; then npm run coverage:ci; fi

matrix:
  include:
    - node_js: "10"
      os: linux
      env:
        - TASK=test-couchdb
        # - CLOUDANT_DATABASE=testdb
        # - CLOUDANT_USER=admin
        # - CLOUDANT_PASSWORD=pass
        # - CLOUDANT_PORT=5984
        # - CLOUDANT_URL=https://admin:pass@localhost:5984
      before_script:
        - echo CLOUDANT_USER && echo CLOUDANT_PORT && echo CLOUDANT_DATABASE
        - curl -X GET http://localhost:${CLOUDANT_PORT}
        - curl -X GET http://localhost:${CLOUDANT_PORT}/_node/couchdb@127.0.0.1/_config/admins
        # - curl -X GET --user "admin:pass" 
        # - curl -s -X PUT http://localhost:5984/_config/admins/admin -d '"pass"'
        # - curl -X PUT http://localhost:5984/testdb

      script:
        - npm run test

branches:
  only:
    - master
