sudo: false
language: node_js
node_js:
  - "10"

os:
  - linux

env: TASK=test
install: cd test && npm ci --ignore-scripts && npm run docker:setup && source cloudant-config.sh && pwd

after_success:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ $(echo $TRAVIS_NODE_VERSION | cut -d'.' -f1) == "10" ]]; then npm run coverage:ci; fi

matrix:
  include:
    - node_js: "10"
      os: linux
      env:
        - TASK=test-couchdb
      before_script:
      script:
        - source cloudant-config.sh
        - npm run build
        - npm run test

branches:
  only:
    - master
